/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package domain;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author PC
 */
public abstract class DomainObject {

    public abstract String getTableName();

    public abstract String getColumnsForAdd();

    public abstract String getParamsForAdd();

    public abstract void setParamsForAdd(PreparedStatement ps, DomainObject domainObject) throws SQLException;

    public boolean containsAutogeneratedKey() {
        return true;//vecinom autogenericki, override u slucaju ako nije
    }

    public abstract void setAutogeneratedKey(long key);

    public abstract String getSelectValues();

    public abstract DomainObject setValuesForGet(ResultSet rs);

    public abstract String getUpdateValues();

    public abstract void setValuesForEdit(PreparedStatement ps);

    public abstract String getDeleteValues();

    public abstract void setValuesForDelete(PreparedStatement ps);

}
