/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form;

import domain.OptionalProgram;
import domain.UserProfile;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import view.components.OptionalProgramsTableModel;
import uicontroller.Controller;

/**
 *
 * @author PC
 */
public class EditPasswordForm extends javax.swing.JDialog {

    private UserProfile user;

    /**
     * Creates new form EditUser
  
     */
    public EditPasswordForm(java.awt.Frame parent, boolean modal, UserProfile user) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.user = user;
        System.out.println(user);
        prepareLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pswCurrentPsw = new javax.swing.JPasswordField();
        pswNewPsw = new javax.swing.JPasswordField();
        pswConfirmPsw = new javax.swing.JPasswordField();
        lblUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Korisnicki profil");

        jLabel3.setText("Korisnicko ime:");

        jLabel1.setText("Trenutna lozinka:");

        jLabel2.setText("Nova lozinka:");

        jLabel4.setText("Potvrdi lozinku:");

        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton2.setText("Otkazi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pswCurrentPsw.setText("jPasswordField1");

        pswNewPsw.setText("jPasswordField1");

        pswConfirmPsw.setText("jPasswordField1");

        lblUsername.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswCurrentPsw, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(pswNewPsw)
                            .addComponent(pswConfirmPsw)
                            .addComponent(lblUsername)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pswCurrentPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pswNewPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pswConfirmPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            if (validation()) {
                int answer=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da promenite lozinku?", "Upozorenje", JOptionPane.YES_NO_OPTION);
                if(answer==JOptionPane.YES_OPTION){
                    try {
                        user.setPassword(new String(pswNewPsw.getPassword()));
                        Controller.getInstance().editUserPassword(user);
                         dispose();
                         JOptionPane.showMessageDialog(this, "Lozinka je uspesno promenjena.", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Greska pri cuvanju izmena nad lozinkom u bazi", "Upozorenje", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.ERROR_MESSAGE);
        }
        


    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pswConfirmPsw;
    private javax.swing.JPasswordField pswCurrentPsw;
    private javax.swing.JPasswordField pswNewPsw;
    // End of variables declaration//GEN-END:variables

    private void prepareLabels() {
        pswConfirmPsw.setText(null);
        pswCurrentPsw.setText(null);
        pswNewPsw.setText(null);
        lblUsername.setText(user.getUsername());
    }

    private boolean validation() throws Exception {
        if (new String(pswNewPsw.getPassword()).isEmpty() || new String(pswConfirmPsw.getPassword()).isEmpty() || new String(pswCurrentPsw.getPassword()).isEmpty()) {
            throw new Exception("Nevalidan unos, odredjena polja su prazna.");
        }
        if (!user.getPassword().equals(new String(pswCurrentPsw.getPassword()))) {
            throw new Exception("Greska, trenutna lozinka nije tacna.");
        }
        if (new String(pswNewPsw.getPassword()).equalsIgnoreCase(user.getUsername()) || new String(pswNewPsw.getPassword()).equalsIgnoreCase(user.getEmployer().getFirstname()) || new String(pswNewPsw.getPassword()).equalsIgnoreCase(user.getEmployer().getLastname())) {
            throw new Exception("Lozinka je slaba, ne mozete koristiti ime, prezime ili username kao lozinku.");
        }
        if (!new String(pswNewPsw.getPassword()).equals(new String(pswConfirmPsw.getPassword()))) {
            throw new Exception("Greska, lozinke se ne poklapaju.");
        }return true;
    }
}
