/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form;

import view.form.util.Mode;
import domain.Parent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import view.components.ParentsTableModel;

/**
 *
 * @author PC
 */
public class EditParentForm extends javax.swing.JDialog {

    private Parent parent;
    private JTable tblParents;
    private int mode;

    /**
     * Creates new form EditParentForm
     */
    public EditParentForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public EditParentForm(java.awt.Frame parent, boolean modal, Parent parent2, JTable tblParents, int mode) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.parent = parent2;
        this.tblParents = tblParents;
        this.mode = mode;
        prepareFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtJmbg = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtAdress = new javax.swing.JTextField();
        txtPhone_Number = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime");

        txtFirstname.setText("jTextField3");

        jLabel2.setText("Prezime");

        txtLastname.setText("jTextField2");

        jLabel3.setText("Adresa");

        jLabel4.setText("Broj telefona");

        jLabel5.setText("JMBG");

        txtJmbg.setText("jTextField1");

        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtAdress.setText("jTextField1");

        txtPhone_Number.setText("jTextField2");

        jButton1.setText("Otkazi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(txtFirstname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAdress)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJmbg, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(txtPhone_Number)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPhone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (mode == Mode.EDIT) {
            try {
                if (validation()) {
                    int answer = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da izmenite roditelja " + parent.getFirstname() + " " + parent.getLastname() + "?", "Upozorenje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (answer == JOptionPane.YES_OPTION) {
                        Parent editedParent = new Parent(parent.getId(), txtFirstname.getText(), txtLastname.getText(), txtAdress.getText(), Long.valueOf(txtPhone_Number.getText()), Long.valueOf(txtJmbg.getText()));
                        ParentsTableModel ptm = (ParentsTableModel) tblParents.getModel();
                        ptm.refreshTable(editedParent);
                        dispose();
                    }
                } 
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(mode==Mode.DELETE){
            int answer = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete roditelja " + parent.getFirstname() + " " + parent.getLastname() + "?", "Upozorenje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (answer == JOptionPane.YES_OPTION) {
                    ParentsTableModel ptm = (ParentsTableModel) tblParents.getModel();
                    ptm.removeFromTable(parent);
                    dispose();
                }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtPhone_Number;
    // End of variables declaration//GEN-END:variables

    private void prepareFields() {
        txtAdress.setText(parent.getAdress());
        txtFirstname.setText(parent.getFirstname());
        txtJmbg.setText(parent.getJmbg().toString());
        txtLastname.setText(parent.getLastname());
        txtPhone_Number.setText(parent.getPhoneNumber().toString());
        if (mode == Mode.DELETE) {
            txtAdress.setEnabled(false);
            txtFirstname.setEnabled(false);
            txtJmbg.setEnabled(false);
            txtLastname.setEnabled(false);
            txtPhone_Number.setEnabled(false);
            btnSave.setText("Obrisi");
        }
        if (mode == Mode.EDIT) {
            btnSave.setText("Sacuvaj");
        }
    }

    private boolean validation() throws Exception {
        String firstname = txtFirstname.getText().trim();
        String lastname = txtLastname.getText().trim();
        String JMBG = txtJmbg.getText().trim();
        String adress = txtAdress.getText().trim();
        String phoneNumber = txtPhone_Number.getText().trim();
        if (firstname.isEmpty() || JMBG.isEmpty() || lastname.isEmpty() || adress.isEmpty() || phoneNumber.isEmpty()) {
            throw new Exception("Nevalidan unos, odredjena polja su prazna.");
        }
        for (int i = 0; i < firstname.length(); i++) {
            if (!Character.isLetter(firstname.charAt(i)) && firstname.charAt(i) != ' ') {
                throw new Exception("Nevalidan unos, ime se moze sastojati iskljucivo od slova.");
            }
        }
        for (int i = 0; i < lastname.length(); i++) {
            if (!Character.isLetter(lastname.charAt(i)) && lastname.charAt(i) != ' ') {
                throw new Exception("Nevalidan unos, prezime se moze sastojati iskljucivo od slova.");
            }
        }
        for (int i = 0; i < JMBG.length(); i++) {
            if (!Character.isDigit(JMBG.charAt(i))) {
                throw new Exception("Nevalidan unos, JMBG se moze sastojati iskljucivo od brojeva.");
            }
        }
        if (firstname.length() > 30 || lastname.length() > 30) {
            throw new Exception("Nevalidan unos, maksimalan broj karaktera za ime i prezime je 30.");
        }
        if (JMBG.length() != 13) {
            throw new Exception("Nevalidan unos, JMBG mora imati tacno 13 cifara.");
        }
        if (adress.length() > 40) {
            throw new Exception("Nevalidan unos, maksimalan broj karaktera za adresu je 40.");
        }
        for (int i = 0; i < phoneNumber.length(); i++) {
            if (!Character.isDigit(phoneNumber.charAt(i))) {
                throw new Exception("Nevalidan unos, broj telefona se moze sastojati iskljucivo od brojeva.");
            }
        }
        return true;
    }
}
