/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import domain.Employer;
import view.form.util.Mode;
import domain.UserProfile;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import thread.TimeThread;
import uicontroller.Controller;
//import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class MainForm extends javax.swing.JFrame {

    private UserProfile user;
//    ImageIcon backgroundImg = new ImageIcon("pozadina.jpg");

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);
        setTime();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        lblImg.setText("");
      

    }

    public MainForm(UserProfile user) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.user = user;
        System.out.println(user);
        fillUser(user);
        setTime();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        lblImg.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        jmMainManu = new javax.swing.JMenuBar();
        jmChild = new javax.swing.JMenu();
        jmiViewChildren = new javax.swing.JMenuItem();
        jmiAddNewChild = new javax.swing.JMenuItem();
        jmiViewSearchedAttendances = new javax.swing.JMenuItem();
        jmParent = new javax.swing.JMenu();
        jmiViewParents = new javax.swing.JMenuItem();
        jmEmployee = new javax.swing.JMenu();
        jmiViewEmployers = new javax.swing.JMenuItem();
        jmiAddNewEmployee = new javax.swing.JMenuItem();
        jmOptionalProgram = new javax.swing.JMenu();
        jmiViewOptionalPrograms = new javax.swing.JMenuItem();
        jmiAddNewOptionalProgram = new javax.swing.JMenuItem();
        jmSettings = new javax.swing.JMenu();
        jmiEditPassword = new javax.swing.JMenuItem();
        jmiEditUserStatus = new javax.swing.JMenuItem();
        jmiLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evidencija");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("Ulogovan korisnik:");

        lblUser.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblUser.setText("user");

        lblTime.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTime.setText("Vreme");

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pozadina_resized_1.png"))); // NOI18N
        lblImg.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(282, 282, 282)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUser))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(499, Short.MAX_VALUE)
                    .addComponent(lblTime)
                    .addContainerGap()))
        );

        jmChild.setText("Dete");

        jmiViewChildren.setText("Prikazi decu");
        jmiViewChildren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewChildrenActionPerformed(evt);
            }
        });
        jmChild.add(jmiViewChildren);

        jmiAddNewChild.setText("Dodaj novo dete");
        jmiAddNewChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewChildActionPerformed(evt);
            }
        });
        jmChild.add(jmiAddNewChild);

        jmiViewSearchedAttendances.setText("Prikazi pohadjanja");
        jmiViewSearchedAttendances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewSearchedAttendancesActionPerformed(evt);
            }
        });
        jmChild.add(jmiViewSearchedAttendances);

        jmMainManu.add(jmChild);

        jmParent.setText("Roditelj");

        jmiViewParents.setText("Prikazi roditelje");
        jmiViewParents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewParentsActionPerformed(evt);
            }
        });
        jmParent.add(jmiViewParents);

        jmMainManu.add(jmParent);

        jmEmployee.setText("Zaposleni");

        jmiViewEmployers.setText("Prikazi zaposlene");
        jmiViewEmployers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewEmployersActionPerformed(evt);
            }
        });
        jmEmployee.add(jmiViewEmployers);

        jmiAddNewEmployee.setText("Dodaj novog zaposlenog");
        jmiAddNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewEmployeeActionPerformed(evt);
            }
        });
        jmEmployee.add(jmiAddNewEmployee);

        jmMainManu.add(jmEmployee);

        jmOptionalProgram.setText("Izborni program");

        jmiViewOptionalPrograms.setText("Prikazi izborne programe");
        jmiViewOptionalPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewOptionalProgramsActionPerformed(evt);
            }
        });
        jmOptionalProgram.add(jmiViewOptionalPrograms);

        jmiAddNewOptionalProgram.setText("Dodaj novi izborni program");
        jmiAddNewOptionalProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewOptionalProgramActionPerformed(evt);
            }
        });
        jmOptionalProgram.add(jmiAddNewOptionalProgram);

        jmMainManu.add(jmOptionalProgram);

        jmSettings.setText("Podesavanja");

        jmiEditPassword.setText("Izmeni lozinku");
        jmiEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditPasswordActionPerformed(evt);
            }
        });
        jmSettings.add(jmiEditPassword);

        jmiEditUserStatus.setText("Izmeni status korisnika");
        jmiEditUserStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditUserStatusActionPerformed(evt);
            }
        });
        jmSettings.add(jmiEditUserStatus);

        jmiLogout.setText("Odjavi se");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jmSettings.add(jmiLogout);

        jmMainManu.add(jmSettings);

        setJMenuBar(jmMainManu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jmiAddNewChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewChildActionPerformed
        //new AddNewChildForm(this, true).setVisible(true);
        new AddNewChildParentForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmiAddNewChildActionPerformed

    private void jmiAddNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewEmployeeActionPerformed
        new AddNewEmployerForm(this, true, Mode.ADD).setVisible(true);
    }//GEN-LAST:event_jmiAddNewEmployeeActionPerformed

    private void jmiAddNewOptionalProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewOptionalProgramActionPerformed
        new AddNewOptionalProgramForm(this, true, Mode.ADD).setVisible(true);
    }//GEN-LAST:event_jmiAddNewOptionalProgramActionPerformed

    private void jmiEditUserStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditUserStatusActionPerformed
        new UsersStatusForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmiEditUserStatusActionPerformed

    private void jmiViewChildrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewChildrenActionPerformed
        new ViewAllChildrenForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmiViewChildrenActionPerformed

    private void jmiViewOptionalProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewOptionalProgramsActionPerformed
        new ViewAllOptionalProgramForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmiViewOptionalProgramsActionPerformed

    private void jmiEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditPasswordActionPerformed
        System.out.println(user);
        new EditPasswordForm(this, true, user).setVisible(true);
    }//GEN-LAST:event_jmiEditPasswordActionPerformed

    private void jmiViewParentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewParentsActionPerformed
        new ViewAllParentsForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmiViewParentsActionPerformed

    private void jmiViewEmployersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewEmployersActionPerformed
        new ViewAllEmployersForm(this, true).setVisible(true);

    }//GEN-LAST:event_jmiViewEmployersActionPerformed

    private void jmiViewSearchedAttendancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewSearchedAttendancesActionPerformed
        new ViewAllAttendancesForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmiViewSearchedAttendancesActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        int answer = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da se odjavite sa sistema?", "Upozorenje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) {
            try {
                user = Controller.getInstance().logout(user);
                JOptionPane.showMessageDialog(this, "Korisnik " + user.getEmployer().toString() + " je uspesno izlogovan", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                System.exit(0);
            } catch (Exception ex) {
                dispose();
            }
        }
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int answer = JOptionPane.showConfirmDialog(this, "Sistem ce vas automatski odjaviti. Da li ste sigurni da zelite da zavrsite sa radom?", "Upozorenje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) {
            try {
                user = Controller.getInstance().logout(user);
                JOptionPane.showMessageDialog(this, "Korisnik " + user.getEmployer().toString() + " je uspesno izlogovan", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                System.exit(0);
            } catch (Exception ex) {
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Radnja otkazana, nastavite sa radom", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmChild;
    private javax.swing.JMenu jmEmployee;
    private javax.swing.JMenuBar jmMainManu;
    private javax.swing.JMenu jmOptionalProgram;
    private javax.swing.JMenu jmParent;
    private javax.swing.JMenu jmSettings;
    private javax.swing.JMenuItem jmiAddNewChild;
    private javax.swing.JMenuItem jmiAddNewEmployee;
    private javax.swing.JMenuItem jmiAddNewOptionalProgram;
    private javax.swing.JMenuItem jmiEditPassword;
    private javax.swing.JMenuItem jmiEditUserStatus;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiViewChildren;
    private javax.swing.JMenuItem jmiViewEmployers;
    private javax.swing.JMenuItem jmiViewOptionalPrograms;
    private javax.swing.JMenuItem jmiViewParents;
    private javax.swing.JMenuItem jmiViewSearchedAttendances;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    private void fillUser(UserProfile user) {
        lblUser.setText(user.getEmployer().toString());
    }

    private void setTime() {
        TimeThread timeThread = new TimeThread(lblTime);
        Thread t = new Thread(timeThread);
        t.start();
    }
}
