/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form;

import domain.Child;
import domain.EditAndDeleteList;
import domain.Employer;
import view.form.util.Mode;
import domain.Parent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import view.components.ChildrenTableModel;
import view.components.EmployersTableModel;
import view.components.ParentsTableModel;
import uicontroller.Controller;

/**
 *
 * @author PC
 */
public class ViewAllEmployersForm extends javax.swing.JDialog {

    /**
     * Creates new form ViewAllEmployersForm
     */
    public ViewAllEmployersForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployers = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbViewAll = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zaposleni");

        tblEmployers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployers.setName(""); // NOI18N
        jScrollPane1.setViewportView(tblEmployers);

        btnEdit.setText("Izmeni");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDetails.setText("Detalji");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnDelete.setText("Obrisi");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Prezime:");

        btnSearch.setText("Pretrazi");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cbViewAll.setText("Prikazi sve");
        cbViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbViewAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbViewAll)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(cbViewAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDetails)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        txtLastname.setEnabled(false);
        btnSearch.setEnabled(false);
        cbViewAll.setEnabled(false);
        Employer employer;
        int selectedRow = tblEmployers.getSelectedRow();
        if (tblEmployers.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati tacno jednog zaposlenog", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                EmployersTableModel etb = (EmployersTableModel) tblEmployers.getModel();
                employer = etb.getEmployer(selectedRow);
                List<Employer> employers = Controller.getInstance().getEmployers(employer);
                if (!employers.isEmpty()) {
                    employer = employers.get(0);
                    JOptionPane.showMessageDialog(this, "Sistem je ucitao zaposlenog.", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                    new AddNewEmployerForm(null, true, employer, tblEmployers, Mode.EDIT).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita zaposlenog.", "Upozorenje", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita zaposlenog.", "Upozorenje", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
   
        Employer employer;
        int selectedRow = tblEmployers.getSelectedRow();
        if (tblEmployers.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati tacno jednog zaposlenog", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                EmployersTableModel etm = (EmployersTableModel) tblEmployers.getModel();
                employer = etm.getEmployer(selectedRow);
                List<Employer> employers = Controller.getInstance().getEmployers(employer);
                if (!employers.isEmpty()) {
                    employer = employers.get(0);
                    JOptionPane.showMessageDialog(this, "Sistem je ucitao zaposlenog.", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                    new DetailsEmployersForm(null, true, employer).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita zaposlenog.", "Upozorenje", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita zaposlenog.", "Upozorenje", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Employer employer;
        int selectedRow = tblEmployers.getSelectedRow();
        if (tblEmployers.getSelectedRowCount() != 1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati tacno jednog zaposlenog", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                EmployersTableModel etb = (EmployersTableModel) tblEmployers.getModel();
                employer = etb.getEmployer(selectedRow);
                List<Employer> employers = Controller.getInstance().getEmployers(employer);
                if (!employers.isEmpty()) {
                    employer = employers.get(0);
                    JOptionPane.showMessageDialog(this, "Sistem je ucitao zaposlenog.", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                    new AddNewEmployerForm(null, true, employer, tblEmployers, Mode.DELETE).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita zaposlenog.", "Upozorenje", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita zaposlenog.", "Upozorenje", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int answer = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da sacuvate sve izmene u bazi? ", "Upozorenje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (answer == JOptionPane.YES_OPTION) {
            EmployersTableModel etm = (EmployersTableModel) tblEmployers.getModel();
            List<Employer> editedEmployers = etm.getEditedEmployers();
            List<Employer> deletedEmployers = etm.getDeletedEmployers();
            try {
                EditAndDeleteList editAndDeleteList=new EditAndDeleteList(editedEmployers, deletedEmployers);
                Controller.getInstance().editAndDeleteEmployers(editAndDeleteList);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio i obrisao zaposlene.", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                dispose();

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti ili obrise zaposlene.", "Upozorenje", JOptionPane.ERROR_MESSAGE);
                fillTable();
            }
        }         
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        cbViewAll.setSelected(false);
//        try {
//            if (validation(txtLastname.getText().trim())) {
        String lastname = txtLastname.getText().trim();
        try {
            List<Employer> employers = new ArrayList<>();
            Employer employer = new Employer();
            employer.setLastname(lastname);
            employers = Controller.getInstance().getEmployers(employer);
            if (!employers.isEmpty()) {
                EmployersTableModel etm = new EmployersTableModel(employers);
                tblEmployers.setModel(etm);
                JOptionPane.showMessageDialog(this, "Sistem je nasao zaposlene po zadatoj vrednosti.", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje zaposlene po zadatoj vrednosti.", "Upozorenje", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska pri pretrazivanju zaposlenog u bazi", "Upozorenje", JOptionPane.ERROR_MESSAGE);
        }
//            }
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, ex.getMessage(), "Upozorenje", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cbViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbViewAllActionPerformed
        fillTable();
    }//GEN-LAST:event_cbViewAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox cbViewAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmployers;
    private javax.swing.JTextField txtLastname;
    // End of variables declaration//GEN-END:variables

    private void fillTable() {
        List<Employer> employers = new ArrayList<>();
        try {
            employers = Controller.getInstance().getAllEmployers();
            EmployersTableModel etb = new EmployersTableModel(employers);
            tblEmployers.setModel(etb);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju liste zaposlenih", "Upozorenje", JOptionPane.ERROR_MESSAGE);
        }

    }

    private boolean validation(String lastname) throws Exception {
        if (lastname.isEmpty()) {
            throw new Exception("Nevalidan unos, odredjena polja su prazna.");
        }
        for (int i = 0; i < lastname.length(); i++) {
            if (!Character.isLetter(lastname.charAt(i)) && lastname.charAt(i) != ' ') {
                throw new Exception("Nevalidan unos, prezime se moze sastojati iskljucivo od slova.");
            }
        }
        if (lastname.length() > 30) {
            throw new Exception("Nevalidan unos, maksimalan broj karaktera za prezime je 30.");
        }
        return true;
    }
}
